# Generated by Django 2.1.4 on 2019-06-24 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cate',
            table='cate',
        ),
        migrations.AlterModelTable(
            name='goods',
            table='goods',
        ),
    ]
